library(ggplot2)
ggplot(test_data, aes(x=Species, y=Pre, color=Post)) + geom_point(size=1) + facet_wrap(~ test_data$Levels)
ggplot(test_data, aes(x=Species, y=test_data$`Pre-Photoynthesis`, color=test_data$`Post-Photosynthesis`)) + geom_point() + facet_wrap(~ test_data$Levels)
ggplot(test_data, aes(x=Levels, y=test_data$`Pre-Photoynthesis`, color=test_data$`Post-Photosynthesis`)) + geom_point() + facet_wrap(~ test_data$Species)
ggplot(test_data, aes(x=Levels, y=test_data$`Pre-Photoynthesis`, color=test_data$'Species')) + geom_point() + facet_wrap(~ test_data$Species)
ggplot(test_data, aes(x=Levels, y=test_data$`Pre-Photoynthesis`, color=test_data$'Species')) + geom_point() + facet_wrap(~ test_data$Levels)
ggplot(test_data, aes(x=Levels, y=test_data$`Post-Photosynthesis`, color=test_data$'Species')) + geom_point() + facet_wrap(~ test_data$Levels)
ggplot(test_data, aes(x=Levels, y=test_data$`Post-Photosynthesis`, color=test_data$'Species')) + geom_point() + facet_wrap(~ test_data$Species)
ggplot(test_data, aes(x=Levels, y=test_data$`Post-Photosynthesis`, color=test_data$'Species')) + geom_density_2d() + facet_wrap(~ test_data$Species)
ggplot(test_data, aes(x=Levels, y=test_data$`Post-Photosynthesis`, color=test_data$'Species')) + geom_boxplot() + facet_wrap(~ test_data$Species)
uglyplot1 <- ggplot(test_data, aes(x=Levels, y=test_data$`Post-Photosynthesis`, color=test_data$'Species')) + geom_violin(fill="light green") + facet_wrap(~ test_data$Species) + ylab("Post-Photosynthesis") + theme_grey() 
ggplot(test_data, aes(x=Levels, y=test_data$`Post-Photosynthesis`, color=test_data$'Species')) + geom_area() + facet_wrap(~ test_data$Species)
print(uglyplot1)
uglyplot2 <- ggplot(test_data, aes(x=test_data$Levels, y=test_data$`Pre-Photoynthesis`, color=test_data$Species)) + geom_point(size=1) +geom_smooth(method = lm, se = FALSE) + ylab("Pre-Photosynthesis") + xlab("Ammonia Levels")
ggsave("uglyplot2.png", width = 5, height = 5)
ggsave("uglyplot1.png", width = 5, height = 5)
uglyplot3 <- ggplot(test_data, aes(x=test_data$Levels, y=test_data$`Post-Photosynthesis`, color=test_data$Species)) + geom_point() +geom_smooth(method = lm, se = FALSE)
ggsave("uglyplot3.png", width = 5, height = 4)
