str(diamonds)
nrow(diamonds) # there are 53940 rows
set.seed(1410)
dsmall <- diamonds[sample(nrow(diamonds), 100), ]
str(dsmall)
task1 <- ggplot(dsmall, aes(x=x, y=y, color=z)) + geom_point(size=1) + facet_wrap(~ dsmall$cut)
print(task1)
task2 <- ggplot(dsmall, aes(x=carat, y=price, color=cut)) + geom_point(size=1) +geom_smooth(method = lm, se = FALSE)
print(task2)
task3 <- ggplot(dsmall, aes(x=carat, colour=clarity)) + geom_density() + facet_wrap(~ dsmall$clarity)
print(task3)
task4 <- ggplot(dsmall, aes(factor(cut), price)) + geom_boxplot()
print(task4)
task5 <- ggplot(dsmall, mapping = aes(x=x, y=y)) + geom_line(aes(colour=x, group=x)) + geom_point(aes(colour=x), size=3, colour= "red") + geom_smooth(colour = "blue", linetype= 2) + xlab("x, in mm") +ylab("y, in mm") 
print(task5)
