---
title: "Project_GEOL590_Proposal"
author: "Marife Anunciado"
date: "March 22, 2017"
output: 
    github_document: default
---

The project proposal will be developed by the researcher, **Marife Anunciado**.


The project proposed will involve package development using the Integration-Manager Workflow system wherein I, as the main researcher have the option to save and maintain a copy of the original project publicly but can authorize and allow other potential researcher to collaborate and create their own output from the original project generated, if changes are necessary to incorporate new dataset into the original dataset on their local repositories.


### **Project:**

The project will demonstrate absorbance of chemical compounds/ bonds found in plastic films using fourier transform infrared spectroscopy. It is aimed to generate a package that will convert original datasets into a log normalized data and convert measurement units into a general and useful form. For the project, wavelengths of absorbance from 600 to 4000 nanometers will be log normalize and mean absorbance of normalized data will be calculated.  Absorbance curve are the expected outputs to visually present the data. 

Data conversion of all generated raw data has been performed and was possible in Excel but observed to be tedious. This package was expected to work to avoid manual conversions from the researcheer's end and limit errors that can be acquire through formula coding in Excel. Although error's can be checked, it has to be individually examined on each rows/columns but through this package, a single generated statement can exactly pinpoint the error that might be encountered while coding.


The developed package was designed for the specific protocols in the laboratory, so this package will be useful to future analysis that involves FTIR analysis, specifically on the raw data processing. Through the package, use of a software-data processing tool will not be necessary to convert raw datasets to view output datasets. The objectives will be to:

  *  Normalize the data from 16 scans for each wavelength of the plastic material;
  *  Summarize and generata a single table showing all the wavelengths in one;
  *  Generate a mean and plot of all the absorbance values of plastic material.

